# Generated by Django 3.2.2 on 2021-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='des',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
