# Generated by Django 3.2.2 on 2021-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='price')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(upload_to='service'),
        ),
    ]
