# Generated by Django 3.2.2 on 2021-05-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='style1')),
            ],
        ),
    ]
